### ISSUE TITLE
Case for if layer > 256*MB needs to be included

### ISSUE THREAD

**Issue by annalysiascowen** [jsingson1024/procreateLayerCalculator#1]
![image](https://github.com/jsingson1024/procreateLayerCalculator/assets/67397391/9121685a-0139-4adb-9ada-7060a04d6d8a)

Elena found that using:

iPad Pro 11 inch 1st Gen
Width: 7016px
Height: 9933px

Returns 3 layers in layer calculator. In Procreate it returns 0. I thiiiiink we are missing the case I have screenshot above? :)

**Comment by jsingson1024** [comment]
Thanks @annalysiascowen I've been meaning to add that since the longest time. 😂

**Comment by jsingson1024** [comment]
Doneskies
